"""Resident architectural skeleton emitted into CLAUDE.md at index time (gated:
indexing.emit_skeleton, default OFF). A compact, regenerated-in-place map of modules (heuristic
role + file/language mix) plus the dependency DIRECTION between them (aggregated resolved call
edges, confidence-filtered). It is a DECOUPLED artifact that goes stale between indexes, so it
carries a freshness stamp and an in-band 'believed-then' honesty block. Builder-pure (reads only
sqlite); the writer does an idempotent marker-bounded splice that never clobbers user content.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

from pandemonium.graph import CALLER_MIN_CONFIDENCE, EDGE_LANGUAGES, GraphIndex
from pandemonium.retrieval.tests_finder import is_test_path
from pandemonium.util import now_iso, repo_id_for

START = "<!-- pandemonium:skeleton:start -->"
END = "<!-- pandemonium:skeleton:end -->"
NOTICE = ("<!-- GENERATED by `pandemonium index` — do not edit between these markers; "
          "overwritten on reindex. -->")
_MAX_MODULES = 15
_MAX_EDGES = 25


def module_key(path: str) -> str:
    """Depth-2 package bucket: a file directly under a top dir -> that dir; nested -> the package
    dir (first two segments); a bare root file -> '(root)'. Depth-1 collapses a whole package to
    one node (verified useless on the live index), so the skeleton uses depth-2."""
    parts = path.split("/")
    if len(parts) <= 1:
        return "(root)"
    if len(parts) == 2:
        return parts[0]
    return "/".join(parts[:2])


def _parse_tags(raw):
    try:
        parsed = json.loads(raw)
    except (ValueError, TypeError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def build_skeleton(settings, sqlite) -> dict:
    repo_id = repo_id_for(settings.repo_root)
    mod_files = defaultdict(list)
    for f in sqlite.files(repo_id):
        mod_files[module_key(f["path"])].append(f)

    domains = defaultdict(Counter)
    entry = defaultdict(set)
    for row in sqlite.chunk_tags(repo_id):
        mod = module_key(row["path"])
        t = _parse_tags(row["tags"])
        for d in t.get("domain", []):
            domains[mod][d] += 1
        for ep in t.get("entrypoints", []):
            entry[mod].add(ep)

    present_langs: set = set()
    modules = []
    for mod, fs in mod_files.items():
        langs = Counter(f["language"] for f in fs if f["language"])
        present_langs |= set(langs)
        dom_lang = langs.most_common(1)[0][0] if langs else "?"
        if all(is_test_path(f["path"]) for f in fs):
            role = "tests"
        elif entry.get(mod):
            role = "entrypoints: " + ", ".join(sorted(entry[mod])[:3])
        elif domains.get(mod):
            role = domains[mod].most_common(1)[0][0]
        else:
            role = f"{dom_lang} module"
        modules.append({"module": mod, "role": role, "files": len(fs),
                        "languages": [lang for lang, _ in langs.most_common()]})
    modules.sort(key=lambda m: -m["files"])

    idx = GraphIndex(sqlite, repo_id)
    counter: Counter = Counter()
    for e in sqlite.relationships_by_type(repo_id, "calls"):
        src = idx.by_id.get(e["source_id"])
        if not src:
            continue
        for sid, conf, ambiguous, _ev in idx.resolve_call(e, src):
            if ambiguous or conf < CALLER_MIN_CONFIDENCE:
                continue
            dst = idx.by_id.get(sid)
            if not dst:
                continue
            sm, dm = module_key(src["path"]), module_key(dst["path"])
            if sm != dm:  # intra-module calls are noise for an architecture map
                counter[(sm, dm)] += 1
    edges = [{"src": s, "dst": d, "weight": w} for (s, d), w in counter.most_common(_MAX_EDGES)]

    uncovered = sorted(lang for lang in present_langs if lang and lang not in EDGE_LANGUAGES)
    return {"name": settings.project_name, "root": str(settings.repo_root),
            "generated_at": now_iso(), "modules": modules[:_MAX_MODULES], "edges": edges,
            "uncovered_languages": uncovered}


def render_skeleton(model: dict) -> str:
    uncov = model.get("uncovered_languages") or []
    out = [
        "## Architectural skeleton (believed-then)",
        f"_Believed as of {model['generated_at']} — regenerated at index time. This is a "
        "DECOUPLED artifact: it goes stale as code changes between indexes (unlike a re-resolved "
        "repo_get). A stale skeleton silently misorients — confirm against live code before "
        "trusting direction._",
        "_Roles are heuristic (path / domain / entrypoint tags). Direction = aggregated resolved "
        "call edges (confidence ≥ 0.6, ambiguous dropped) — a floor, not a ceiling. Edges "
        "exist only for Python/C++/C#/JS/TS/Dart"
        + (f"; modules in other languages ({', '.join(uncov)}) get a role but NO direction" if uncov else "")
        + ". Cannot see: dynamic/runtime dispatch, cross-language calls, import-only coupling. "
        "Cost: this block spends always-resident context budget every session._",
        "",
        "### Modules (role · files)",
    ]
    if model["modules"]:
        for m in model["modules"]:
            lang = ("; " + "/".join(m["languages"][:3])) if m["languages"] else ""
            out.append(f"- `{m['module']}` — {m['role']} ({m['files']} files{lang})")
    else:
        out.append("- (nothing indexed yet)")
    out.append("\n### Dependency direction (who calls whom)")
    if model["edges"]:
        out += [f"- `{e['src']}` → `{e['dst']}` ({e['weight']})" for e in model["edges"]]
    else:
        out.append("- (no confidently-resolved cross-module calls)")
    return "\n".join(out)


def _strip_stamp(block: str) -> str:
    return "\n".join(line for line in block.splitlines() if "Believed as of" not in line)


def write_skeleton_into_claude_md(repo_root, body: str) -> bool:
    """Idempotent marker-bounded write. Returns True if CLAUDE.md changed. Requires BOTH markers
    for an in-place replace; otherwise APPENDS a fresh block (never clobbers user content). Skips
    the write when only the timestamp would change (anti-churn)."""
    block = f"{START}\n{NOTICE}\n{body}\n{END}"
    path = Path(repo_root) / "CLAUDE.md"
    if not path.exists():
        path.write_text(block + "\n", encoding="utf-8")
        return True
    text = path.read_text(encoding="utf-8")
    i, j = text.find(START), text.find(END)
    if i != -1 and j != -1 and j > i:
        if _strip_stamp(text[i:j + len(END)]) == _strip_stamp(block):
            return False
        path.write_text(text[:i] + block + text[j + len(END):], encoding="utf-8")
        return True
    sep = "" if text.endswith("\n") else "\n"
    path.write_text(f"{text}{sep}\n{block}\n", encoding="utf-8")
    return True
